
enum class eComponentType
{
	UNKOWN_COMPONENT = -1,

	TRANSFORM_COMPONENT = 1,
	SCRIPT_COMPONENT = 2,
	PHYSICS_COMPONENT = 3,
	COLLIDER_COMPONENT = 4,
	RENDER_COMPONENT = 5,
	PARTICLE_COMPONENT = 6,
	CAMERA_COMPONENT = 7,
};
